# Washington Housing- Statistical Analysis

## Import HouseValue Data (Zillow-ZHVI)

In [1]:
import pandas as pd
import requests

In [2]:
# Since source data has been stored in the project Data folder, we will save the path to our dataset for reproducability. 
from pathlib import Path

DATA_DIR = Path('../data')

county_zhvi_path = DATA_DIR / 'County_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv'

In [3]:
housing_value = pd.read_csv(county_zhvi_path)
housing_value.info()

<class 'pandas.DataFrame'>
RangeIndex: 3071 entries, 0 to 3070
Columns: 329 entries, RegionID to 2026-08-31
dtypes: float64(320), int64(4), str(5)
memory usage: 7.8 MB

## Data Cleansing

In [4]:
housing_value.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,...,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,210217.606330,...,876483.587025,880007.553689,881688.903831,881664.429746,879853.109780,877155.644127,874790.006512,872663.237476,872220.753950,873008.422497
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,152726.258141,...,327258.568438,328895.003922,330363.857134,332095.627821,333712.155986,335053.111563,336017.428066,337263.418771,339162.650330,341569.750726
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,113021.492070,...,283353.950111,283400.843255,283252.913344,282917.697617,282310.098950,281596.697303,280609.689845,279554.676080,278797.691949,278517.967005
3,2402,3,Maricopa County,county,AZ,AZ,"Phoenix-Mesa-Chandler, AZ",4,13,146106.503852,...,459582.164053,460367.019987,461220.420505,461894.030995,461740.421962,460735.657745,459147.558173,457589.893930,456733.110469,456252.050797
4,2841,4,San Diego County,county,CA,CA,"San Diego-Chula Vista-Carlsbad, CA",6,73,216416.160304,...,925424.340732,927598.249086,928828.819170,929848.898004,930228.329587,930115.693184,929543.266462,928860.113917,929330.517880,930799.654961

In [5]:
housing_value.columns

Index(['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName',
       'State', 'Metro', 'StateCodeFIPS', 'MunicipalCodeFIPS', '2000-01-31',
       ...
       '2025-11-30', '2025-12-31', '2026-01-31', '2026-02-28', '2026-03-31',
       '2026-04-30', '2026-05-31', '2026-06-30', '2026-07-31', '2026-08-31'],
      dtype='str', length=329)

In [6]:
# to display all columns
pd.set_option('display.max_columns', None)
housing_value.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,StateCodeFIPS,MunicipalCodeFIPS,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30,2022-10-31,2022-11-30,2022-12-31,2023-01-31,2023-02-28,2023-03-31,2023-04-30,2023-05-31,2023-06-30,2023-07-31,2023-08-31,2023-09-30,2023-10-31,2023-11-30,2023-12-31,2024-01-31,2024-02-29,2024-03-31,2024-04-30,2024-05-31,2024-06-30,2024-07-31,2024-08-31,2024-09-30,2024-10-31,2024-11-30,2024-12-31,2025-01-31,2025-02-28,2025-03-31,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31,2026-02-28,2026-03-31,2026-04-30,2026-05-31,2026-06-30,2026-07-31,2026-08-31
0,3101,0,Los Angeles County,county,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",6,37,210217.606330,210455.313210,211332.872795,213070.407984,215280.130493,217394.174469,219524.653485,221715.785519,223745.635315,225365.980782,226843.629878,228250.604205,229179.845634,230047.247547,231273.361082,233365.681362,235671.549613,238003.894515,240392.303733,242849.073694,245055.836790,247212.821841,249168.058998,251190.716681,252707.595774,254415.408860,256686.447296,259871.268657,263519.584804,267156.033247,271523.227746,276196.872911,281175.808280,285761.907384,290239.625700,294494.466212,297906.623349,300915.862958,304385.334345,308316.405266,313137.776548,317354.882046,322708.524116,328406.109753,334690.428069,339861.521120,344620.391950,349493.591005,354980.797274,360853.508586,367147.737053,374979.718600,384693.430115,394724.057079,404106.248706,412626.505597,422008.655705,431232.439745,438306.773007,444001.354093,448270.746074,454231.604522,460376.684465,467309.927968,473480.406052,480341.452685,488031.613773,496498.641795,505125.888667,514593.579500,522320.286410,528933.697411,534503.097210,539295.105125,544208.229076,548172.220564,553250.601592,557658.231779,560826.196319,562970.522440,562520.734710,562177.509001,561975.465072,563204.346107,563884.990705,563784.090633,562525.618134,561653.040458,559440.256501,556759.898582,552396.123774,547679.078800,542582.408009,536634.637325,530962.133307,525105.073686,520600.193464,515140.657360,506863.639944,495109.825353,481318.705704,468010.952130,454831.715541,442822.290275,433225.323734,425359.693065,417915.956410,408601.671505,400835.119081,395262.413695,391832.158594,388457.803016,385214.079713,381231.179680,377883.665784,375707.652496,374729.812039,374312.419738,375194.815836,378439.248452,380706.135930,381006.869978,381609.707272,383326.880135,386599.570921,386587.618306,385161.967354,381373.241581,377480.297783,373644.643986,370181.250812,368541.110735,367577.370462,367682.754238,366578.777455,365441.251733,361997.084584,360421.388625,358912.138542,356947.968062,353347.997402,349351.120336,347712.670865,346976.600738,346535.829555,345119.799994,342725.389843,340256.428400,338849.382306,339016.959870,340671.946680,344535.037790,350136.086494,356867.596476,363723.259214,370528.075434,375315.503820,377892.169749,378544.147624,380492.574393,384781.443060,391171.432544,398605.809703,406934.683568,416051.742720,425295.875899,432952.931986,438979.173591,441707.359155,442541.480480,442154.197621,443317.407736,445257.601718,447508.285514,449819.075292,453238.919075,458598.837696,464740.038020,470807.008651,475919.236422,478916.573783,480167.234246,479832.961800,479745.042204,480302.061889,481729.955575,481993.005614,480655.794554,477727.889933,475009.443787,471887.769782,468921.147369,471191.351665,479494.384397,490918.015313,500023.062464,505859.252880,510812.628649,510203.759229,505791.300220,498605.568463,494896.413074,494476.884623,496644.346349,504506.195525,516119.565656,529385.858179,539261.647852,545982.078450,551300.347950,551207.042348,548796.488233,545092.921548,545596.601433,547450.687809,550471.703132,556802.641365,566632.810739,577883.480483,587251.193846,594378.548666,599355.121989,604533.584683,611495.417721,620461.763858,629179.058172,635342.146390,638729.912263,636525.071857,630017.820613,621579.728281,615477.239488,611861.722822,609819.968448,610911.440203,615537.708233,622742.377932,630005.872577,636563.156419,642640.932621,646052.856949,647272.503216,647222.143457,647306.761017,645679.041907,642416.678843,642583.178080,648528.206928,660457.851677,674084.931463,688775.214734,702688.078163,711316.266511,716213.817610,718179.986493,724145.609023,733073.164955,744309.822767,756328.845059,765719.957242,773345.869288,779533.302808,786698.451047,794871.114405,804168.809506,814853.485948,826772.588084,837574.938983,846467.122368,851695.558558,854414.094489,852781.046989,848690.980196,843829.390835,840442.965042,837650.763668,829309.557843,817726.076800,806697.564156,802804.447744,805038.321725,811396.304373,821898.283375,834933.428938,848029.234687,858689.591057,866697.302465,871661.870197,870633.876594,865791.829388,861947.505717,862591.692496,865795.217037,867909.177360,871601.191126,876861.198830,883555.909018,888750.356562,892922.955623,896372.974405,895593.386107,891779.133609,884866.938654,879512.499270,874473.519449,870275.198683,868351.199259,868315.469476,870417.973438,873252.449899,876483.587025,880007.553689,881688.903831,881664.429746,879853.109780,877155.644127,874790.006512,872663.237476,872220.753950,873008.422497
1,139,1,Cook County,county,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",17,31,152726.258141,152695.605983,152947.098092,153670.289696,154595.756245,155562.367546,156454.916964,157717.973164,159188.469080,160959.620076,162971.152930,164940.730499,166568.213429,167554.273304,168501.661238,169543.361931,170733.228834,171871.938703,172814.792632,174098.435843,175593.572654,177476.026368,179337.502187,180944.180865,182293.824719,183292.430540,184412.078930,185381.411738,186396.745665,187226.662424,188267.646711,189731.633137,191571.435071,193523.101948,195258.445913,196983.780398,198566.041244,199990.144928,201121.324756,202409.469226,203371.251767,204327.871993,205020.291083,206201.628649,207652.484268,209467.068101,211316.213195,213119.786660,214899.912769,216279.653911,217448.613326,218782.569552,220426.731964,222328.057500,224024.792809,225911.003590,227728.835429,229832.152336,232128.916124,234605.609114,236755.704359,238563.387338,240148.412587,241917.540445,243852.954864,245896.041655,247865.154724,249904.089395,252316.402500,254851.314352,257549.443642,260130.803435,262516.342137,264519.652456,266342.225184,267868.673811,269153.846189,269839.883156,270324.650720,270459.178039,270374.645157,270050.571575,269967.202363,270349.280049,271344.248649,272505.758623,273421.327384,273754.570242,273644.395419,273265.770304,272663.896678,272013.225156,270920.597176,269852.130127,268680.265964,267316.380469,266276.293621,263496.133094,263046.269942,260337.802565,259837.447213,256630.317167,255483.218344,252405.161167,250062.959085,246127.407579,242701.997456,238358.786715,233677.321426,229891.678464,225966.014512,224049.818168,221623.011532,220491.205335,218939.333346,217703.046547,215075.775948,212520.317869,209657.567013,208624.536028,207301.414930,207048.345594,205378.700665,205767.666153,205089.652245,205783.914567,203491.977385,201697.961241,198913.063102,196788.575801,194094.089819,191356.603786,189065.731309,186888.495364,185529.035749,183891.842177,183173.964657,181931.558385,181512.250477,180454.372181,179417.360743,177015.714132,175212.986934,172531.321183,170825.663485,168654.479221,167268.002679,165636.395075,164124.075282,163247.153691,163186.132819,163440.839358,163765.760894,163528.656544,162827.650869,162389.946533,162839.521500,164249.142553,165652.213200,167614.359515,169272.314037,171458.308378,173088.734398,175025.010726,176862.266646,179233.569554,181704.705855,184192.580988,186068.940708,187880.684388,189418.842600,190840.155265,192207.409325,193443.913400,194728.732364,195701.474060,196607.652268,197548.804892,198479.339825,199262.725555,199724.435097,199839.457743,200278.869328,200735.621629,201840.179333,202781.135512,203891.876239,204698.886081,205489.240930,206663.508487,207971.948857,209432.361371,210811.703951,212295.797374,213278.466694,214258.746377,215149.951366,216115.460083,216512.665221,216715.378480,217024.417612,217890.753150,218947.484872,220422.844349,221920.639854,223689.041845,225550.914830,226819.056111,227635.050788,227474.144779,227374.902409,227266.099699,228063.543953,229280.054746,230717.201053,232200.911857,233941.784740,235810.686655,238072.498924,239849.434417,241025.735281,240798.633946,240310.567120,239802.792701,239655.467667,239676.468493,239743.957989,240081.619030,240647.096699,241712.870270,242682.160554,243457.476104,243549.298144,243601.578954,243283.908487,242970.691106,242184.609200,241882.046583,241913.145521,242511.454191,243814.171480,245636.743093,247784.746947,249059.720970,249273.221637,248527.061854,247618.250541,247558.232776,248926.379401,251323.903718,254247.893173,257198.193845,260256.198508,263904.235168,267800.054714,271377.113113,274151.700747,276485.515016,278336.735867,279327.049229,279113.565912,278768.263369,278961.446519,280158.416974,282575.349420,286450.744295,291425.519410,296152.634239,298783.798990,299999.617653,299510.355689,298182.947614,295924.093250,294016.283106,293079.906242,292645.114806,291894.444923,291508.266475,291845.030952,293354.957270,294948.940176,296738.356946,298724.633250,301121.345872,303124.748337,304625.768432,305561.712857,306032.653405,306273.703919,307250.127330,309336.980211,312078.768892,313978.496159,315071.368769,315753.031159,316607.479457,317302.378819,317671.437648,318079.247504,318769.685801,319627.341390,320509.446369,321019.316844,321292.146248,321278.974296,321290.428580,322044.467027,322981.586925,324378.643021,325713.214230,327258.568438,328895.003922,330363.857134,332095.627821,333712.155986,335053.111563,336017.428066,337263.418771,339162.650330,341569.750726
2,1090,2,Harris County,county,TX,TX,"Houston-The Woodlands-Sugar Land, TX",48,201,113021.492070,112992.475317,112826.462131,112758.195487,112731.487383,112924.120145,113141.506183,113455.548141,113864.427599,114208.516208,114768.152022,115363.984830,115653.082079,115617.871448,115164.707653,114903.111409,114831.049404,114959.612897,115141.382874,115116.239193,115220.224035,115435.663874,115738.021267,115972.444274,116083.513225,116199.834417,116559.556315,117127.951299,117729.786862,118229.654534,118732.683196,119330.927834,119899.633143,120331.699566,120670.135894,120912.737609,121157.405785,121297.734576,121541.229867,121781.815192,122058.109480,122267.967852,122474.552823,122730.120529,122912.497574,123114.804333,123282.294758,123534.163778,123865.388142,124678.173949,126197.136428,127614.222947,129009.466793,129545.185739,130393.178056,130945.622652,131720.518727,132366.136871,133009.001781,133758.802610,134446.671162,135091.601634,135557.432759,135946.598993,136096.426603,136235.171802,136246.359692,136181.257906,136023.592958,135822.363248,135906.441987,135964.583213,136058.041504,135891.208967,135871.937176,135985.991306,136495.602722,136996.491987,137559.763003,138056.123486,138678.216942,139430.814878,140088.144258,140729.375271,141024.707957,140957.829018,140633.227337,140659.252681,141041.508486,141678.465143,142084.367341,142528.156626,142892.386216,143245.576412,143499.972153,143720.194899,143395.315783,142808.251540,142163.226486,141911.519556,141625.375903,141268.153123,140953.799014,140512.347393,139858.406930,139150.608615,138267.186994,137304.390225,136335.101780,135987.113727,135918.612540,136080.143089,136312.973441,136753.782934,137296.438123,137555.295386,137509.387160,137116.512949,136982.387973,137048.668100,137003.949651,136918.364086,137015.003541,137423.971593,137783.587182,137720.276264,137045.861863,135790.356481,134616.982361,133710.527140,133213.864615,132780.738493,132282.355646,131701.252589,130865.136517,130119.254110,129528.926863,129177.251581,129070.462328,129102.715566,129042.197367,128861.166245,128088.803762,127400.022207,127033.856569,127196.203250,127348.141207,127333.645237,127286.702379,127497.516218,127864.586584,128305.594572,128623.547564,128839.882928,129049.784922,129189.289109,129433.514649,129855.406977,130673.209432,131627.672807,132841.957406,134257.479064,135826.608236,137401.181532,138725.436442,140141.474747,141476.411515,142865.742458,144172.060589,145574.228499,147078.324112,148537.386929,149985.561278,151332.474859,152840.958467,154337.709579,155722.716985,156871.520851,158219.990344,159752.565622,161565.020541,163249.256381,164893.549028,166287.155538,167521.102253,168726.534053,169920.942108,171165.444173,172202.076158,173174.416255,174059.113400,175071.311866,176217.964710,177383.176692,178195.200304,178930.543303,179560.745784,180319.506262,180804.212920,181250.748239,181833.093527,182609.239526,183540.421644,184389.839166,185074.210855,185515.586866,186106.997623,186873.705112,187586.190579,188212.518086,188600.303275,189077.433695,189506.414769,190179.702338,190951.801244,191763.135825,192517.706707,193157.442511,193968.081659,194802.504494,195785.555023,196672.154010,197665.762840,198534.633120,199410.168261,200190.493934,201051.108540,201968.405514,202924.360991,203906.574960,204795.554166,205431.724528,205868.999602,206184.920440,206470.167005,206811.606337,207250.845931,207911.403905,208819.377511,209816.395895,210793.545595,211610.533584,212359.077275,212858.006131,212917.490418,212946.715229,213341.999853,214405.474695,216030.050743,218134.273506,220795.658152,223460.812784,226159.906106,228784.335610,231750.517419,234934.039047,238620.625878,242644.900581,246131.622165,248589.804199,250193.849019,252176.195953,254916.252886,258163.715540,262648.971115,267969.612440,274164.202685,279944.795189,285117.502161,289513.955852,292589.839441,294046.252288,294227.587255,293905.689780,293458.698245,292404.396801,290787.098625,289129.280539,287935.446110,287345.744029,287369.246982,288051.539763,288863.517019,289704.433403,290052.783848,290098.519366,289839.403307,289538.739013,289653.437302,290130.628892,291164.588632,292240.697556,292851.102549,292729.172113,292347.536554,291997.712757,291775.908448,291397.610654,290932.185083,290692.436864,290495.335619,290190.741481,289369.774633,288319.792504,287303.641221,286244.151701,285371.740952,284607.334836,284047.682456,283587.707716,283353.950111,283400.843255,283252.913344,282917.697617,282310.098950,281596.697303,280609.689845,279554.676080,278797.691949,278517.967005

Notes on housing value dataset:
* The dataset currently includes all states. We need to filter and get WA state data.
* County information is stored in "RegionName" column.
* Additionally, Monthly home values (ZHVI) are stored in separate date columns.

In [7]:
# Identify columns containing monthly dates
date_cols = [
    col for col in housing_value.columns
    if col[:4].isdigit()
]

# Convert to tidy format
housing_tidy = housing_value.melt(
    id_vars=["RegionID", "RegionName", "State",
             "StateCodeFIPS", "MunicipalCodeFIPS"],
    value_vars=date_cols,
    var_name="Date",
    value_name="HomeValue"
)

housing_tidy["Date"] = pd.to_datetime(housing_tidy["Date"])

In [8]:
housing_tidy

,RegionID,RegionName,State,StateCodeFIPS,MunicipalCodeFIPS,Date,HomeValue
0,3101,Los Angeles County,CA,6,37,2000-01-31,210217.606330
1,139,Cook County,IL,17,31,2000-01-31,152726.258141
2,1090,Harris County,TX,48,201,2000-01-31,113021.492070
3,2402,Maricopa County,AZ,4,13,2000-01-31,146106.503852
4,2841,San Diego County,CA,6,73,2000-01-31,216416.160304
...,...,...,...,...,...,...,...
982715,846,Banner County,NE,31,7,2026-08-31,386547.922603
982716,1648,Daggett County,UT,49,9,2026-08-31,374740.704413
982717,1432,Thomas County,NE,31,171,2026-08-31,193738.690333
982718,2794,McPherson County,NE,31,117,2026-08-31,357943.402733
982719,2825,Petroleum County,MT,30,69,2026-08-31,210871.592105

In [9]:
wa_housing = housing_tidy[
    (housing_tidy["State"] == "WA") &
    (housing_tidy["Date"].dt.year.between(2015, 2024))
].copy()
wa_housing

,RegionID,RegionName,State,StateCodeFIPS,MunicipalCodeFIPS,Date,HomeValue
552791,207,King County,WA,53,33,2015-01-31,399866.644232
552840,1322,Pierce County,WA,53,53,2015-01-31,240852.011823
552856,2847,Snohomish County,WA,53,61,2015-01-31,310496.423523
552912,2033,Spokane County,WA,53,63,2015-01-31,174516.971052
552921,448,Clark County,WA,53,11,2015-01-31,255172.285498
...,...,...,...,...,...,...,...
920588,1883,Lincoln County,WA,53,43,2024-12-31,318741.346071
920864,511,Ferry County,WA,53,19,2024-12-31,270772.353516
921074,2868,Wahkiakum County,WA,53,69,2024-12-31,385642.971350
921102,2217,Columbia County,WA,53,13,2024-12-31,264617.091014
921212,2305,Garfield County,WA,53,23,2024-12-31,214397.329064

In [10]:
print("Shape:", wa_housing.shape)
print("Total County (RegionName):",wa_housing["RegionName"].nunique())
print("Minimum Date (Earliest):",wa_housing["Date"].min())
print("Maximum Date (Latest):",wa_housing["Date"].max())
print("Total Missing Data:\n",wa_housing.isna().sum())

Shape: (4680, 7)
Total County (RegionName): 39
Minimum Date (Earliest): 2015-01-31 00:00:00
Maximum Date (Latest): 2024-12-31 00:00:00
Total Missing Data:
 RegionID              0
RegionName            0
State                 0
StateCodeFIPS         0
MunicipalCodeFIPS     0
Date                  0
HomeValue            13
dtype: int64

In [11]:
# Calcualted column "CountyFIPS" based on StateCodeFIPS and Municipal CodeFIPS
wa_housing["CountyFIPS"] = wa_housing["StateCodeFIPS"].astype(str).str.zfill(2) + wa_housing["MunicipalCodeFIPS"].astype(str).str.zfill(3)

In [12]:
wa_housing.columns

Index(['RegionID', 'RegionName', 'State', 'StateCodeFIPS', 'MunicipalCodeFIPS',
       'Date', 'HomeValue', 'CountyFIPS'],
      dtype='str')

* So far we have converted the dataset to tidy format
* Dataset has been filtered to include: Washington state only
* Dataset has been filtered to include: from years 2015 to 2024
* It seems like there is one row with missing HomeValue

In [13]:
wa_housing.info()

<class 'pandas.DataFrame'>
Index: 4680 entries, 552791 to 921212
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   RegionID           4680 non-null   int64
 1   RegionName         4680 non-null   str
 2   State              4680 non-null   str
 3   StateCodeFIPS      4680 non-null   int64
 4   MunicipalCodeFIPS  4680 non-null   int64
 5   Date               4680 non-null   datetime64[us]
 6   HomeValue          4667 non-null   float64
 7   CountyFIPS         4680 non-null   str
dtypes: datetime64[us](1), float64(1), int64(3), str(3)
memory usage: 427.0 KB

In [14]:
# Investigate the missing homevalue 
wa_housing[wa_housing["HomeValue"].isna()]

,RegionID,RegionName,State,StateCodeFIPS,MunicipalCodeFIPS,Date,HomeValue,CountyFIPS
555653,2217,Columbia County,WA,53,13,2015-01-31,NaN,53013
558724,2217,Columbia County,WA,53,13,2015-02-28,NaN,53013
561795,2217,Columbia County,WA,53,13,2015-03-31,NaN,53013
564866,2217,Columbia County,WA,53,13,2015-04-30,NaN,53013
567937,2217,Columbia County,WA,53,13,2015-05-31,NaN,53013
571008,2217,Columbia County,WA,53,13,2015-06-30,NaN,53013
574079,2217,Columbia County,WA,53,13,2015-07-31,NaN,53013
577150,2217,Columbia County,WA,53,13,2015-08-31,NaN,53013
580221,2217,Columbia County,WA,53,13,2015-09-30,NaN,53013
583292,2217,Columbia County,WA,53,13,2015-10-31,NaN,53013
586363,2217,Columbia County,WA,53,13,2015-11-30,NaN,53013
589434,2217,Columbia County,WA,53,13,2015-12-31,NaN,53013
592505,2217,Columbia County,WA,53,13,2016-01-31,NaN,53013

* We are missing Home value data for the entire year in 2015 for Columbia County and 1 month in 2016.
* For now we will leave this nan as we have to group by county, year to calculate yearly average.
* Since Home value data for the entire year of 2015 is missing for Columbi acounty, we will have one row with no average house value.

In [15]:
# Extract year
wa_housing["Year"] = wa_housing["Date"].dt.year

# Aggregate monthly ZHVI into annual values
housing_annual = wa_housing.groupby(
        ["CountyFIPS", "RegionName", "Year"],
        as_index=False
    ).agg(
        AvgHomeValue=("HomeValue", "mean"),
        MonthsAvailable=("HomeValue", "count")
    )


housing_annual.head()

  CountyFIPS    RegionName  Year   AvgHomeValue  MonthsAvailable
0      53001  Adams County  2015  139521.505277               12
1      53001  Adams County  2016  145808.702755               12
2      53001  Adams County  2017  155473.557623               12
3      53001  Adams County  2018  170273.632919               12
4      53001  Adams County  2019  184500.979061               12

In [16]:
housing_annual.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CountyFIPS       390 non-null    str
 1   RegionName       390 non-null    str
 2   Year             390 non-null    int32
 3   AvgHomeValue     389 non-null    float64
 4   MonthsAvailable  390 non-null    int64
dtypes: float64(1), int32(1), int64(1), str(2)
memory usage: 21.2 KB

In [17]:
housing_clean = housing_annual.rename(columns={"RegionName": "county",
                                               "Year": "year", 
                                               "CountyFIPS": "county_fips", 
                                               "AvgHomeValue": "average_zhvi"}).copy()
housing_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   county_fips      390 non-null    str
 1   county           390 non-null    str
 2   year             390 non-null    int32
 3   average_zhvi     389 non-null    float64
 4   MonthsAvailable  390 non-null    int64
dtypes: float64(1), int32(1), int64(1), str(2)
memory usage: 21.2 KB

In [18]:
housing_clean = housing_clean[['county_fips', 'county', 'year', 'average_zhvi']]
housing_clean.head()

  county_fips        county  year   average_zhvi
0       53001  Adams County  2015  139521.505277
1       53001  Adams County  2016  145808.702755
2       53001  Adams County  2017  155473.557623
3       53001  Adams County  2018  170273.632919
4       53001  Adams County  2019  184500.979061

In [19]:
housing_clean.to_csv(
    DATA_DIR / 'housing_clean.csv',
    encoding='utf-8-sig',
    index=False
)

## Import Median Household Income Data (Census)

In [20]:
# Since source data has been stored in the project Data folder, we will save the path to our dataset for reproducability. 
median_income_path = DATA_DIR / 'WA_Median_Income_2015_2024.csv'

In [21]:
median_income = pd.read_csv(median_income_path)

In [22]:
median_income.head()

,County,MedianIncome,state,county,Year,CountyFIPS
0,"Grays Harbor County, Washington",43538,53,27,2015,53027
1,"Wahkiakum County, Washington",44485,53,69,2015,53069
2,"Grant County, Washington",48714,53,25,2015,53025
3,"Snohomish County, Washington",70722,53,61,2015,53061
4,"Klickitat County, Washington",48319,53,39,2015,53039

In [23]:
median_income.tail()

,County,MedianIncome,state,county,Year,CountyFIPS
385,"Wahkiakum County, Washington",62653,53,69,2024,53069
386,"Walla Walla County, Washington",74202,53,71,2024,53071
387,"Whatcom County, Washington",81784,53,73,2024,53073
388,"Whitman County, Washington",55406,53,75,2024,53075
389,"Yakima County, Washington",70656,53,77,2024,53077

In [24]:
median_income.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   County        390 non-null    str
 1   MedianIncome  390 non-null    int64
 2   state         390 non-null    int64
 3   county        390 non-null    int64
 4   Year          390 non-null    int64
 5   CountyFIPS    390 non-null    int64
dtypes: int64(5), str(1)
memory usage: 28.4 KB

County FIPS seems to be an identifyer. So lets fix the datatype

In [25]:
median_income['CountyFIPS'] = median_income['CountyFIPS'].astype('str').str.zfill(5) # converts integer values to string and add zeros if needed for consistent formatting
median_income.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   County        390 non-null    str
 1   MedianIncome  390 non-null    int64
 2   state         390 non-null    int64
 3   county        390 non-null    int64
 4   Year          390 non-null    int64
 5   CountyFIPS    390 non-null    str
dtypes: int64(4), str(2)
memory usage: 30.3 KB

In [26]:
median_income["County"].unique()

<ArrowStringArray>
['Grays Harbor County, Washington',    'Wahkiakum County, Washington',
        'Grant County, Washington',    'Snohomish County, Washington',
    'Klickitat County, Washington',     'Okanogan County, Washington',
     'Kittitas County, Washington',       'Benton County, Washington',
        'Clark County, Washington',       'Asotin County, Washington',
        'Adams County, Washington',     'Garfield County, Washington',
        'Mason County, Washington',       'Skagit County, Washington',
      'Stevens County, Washington',      'Spokane County, Washington',
      'Lincoln County, Washington',       'Chelan County, Washington',
    'Jefferson County, Washington',       'Kitsap County, Washington',
         'King County, Washington',      'Pacific County, Washington',
 'Pend Oreille County, Washington',     'San Juan County, Washington',
     'Skamania County, Washington',      'Whitman County, Washington',
       'Yakima County, Washington',      'Clallam County, Washington',
      'Cowlitz County, Washington',        'Ferry County, Washington',
        'Lewis County, Washington',      'Douglas County, Washington',
       'Island County, Washington',       'Pierce County, Washington',
     'Franklin County, Washington',  'Walla Walla County, Washington',
      'Whatcom County, Washington',     'Thurston County, Washington',
     'Columbia County, Washington']
Length: 39, dtype: str

In [27]:
median_income_clean = median_income.rename(columns= { "CountyFIPS": "county_fips",
                                                      "County": "county", 
                                                     "Year": "year",
                                                     "MedianIncome": "median_income"                                               
}).copy()

In [28]:
median_income_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   county         390 non-null    str
 1   median_income  390 non-null    int64
 2   state          390 non-null    int64
 3   county         390 non-null    int64
 4   year           390 non-null    int64
 5   county_fips    390 non-null    str
dtypes: int64(4), str(2)
memory usage: 30.3 KB

In [29]:
median_income_clean= median_income_clean[['county_fips', 'year', 'median_income']]
median_income_clean.head()

  county_fips  year  median_income
0       53027  2015          43538
1       53069  2015          44485
2       53025  2015          48714
3       53061  2015          70722
4       53039  2015          48319

In [30]:
median_income_clean.to_csv(
    DATA_DIR / 'median_indome_clean.csv',
    encoding='utf-8-sig',
    index=False
)

## Import Unemployment Rate (BLS)

In [70]:
IN_PATH = DATA_DIR / "WA_Unemployment_2015_2024.csv"


OUT_PATH = DATA_DIR / "cleaned_unemployment_rate.csv"
 
SEATTLE_METRO = ["King", "Pierce", "Snohomish"]
EASTERN_WA = ["Adams", "Ferry", "Lincoln", "Pend Oreille", "Spokane", "Stevens", "Whitman"]

In [71]:
# Load data set
df = pd.read_csv(IN_PATH, dtype={"CountyFIPS": str})

In [72]:
df.head()

  CountyFIPS                    County  Year  UnemploymentRate
0      53001  Adams County, Washington  2015               7.0
1      53001  Adams County, Washington  2016               6.9
2      53001  Adams County, Washington  2017               6.2
3      53001  Adams County, Washington  2018               6.0
4      53001  Adams County, Washington  2019               6.3

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CountyFIPS        390 non-null    str
 1   County            390 non-null    str
 2   Year              390 non-null    int64
 3   UnemploymentRate  390 non-null    float64
dtypes: float64(1), int64(1), str(2)
memory usage: 24.2 KB

* The dataset contains 390 observations with no missing values.
* County FIPS is stored as a string to preserve its identifier format.
* County names include the state name and will be standardized.
* Column names will be standardized for merging.

In [74]:
# Clean data set
df = df.rename(columns={
    "CountyFIPS": "county_fips",
    "County": "county_full",
    "Year": "year",
    "UnemploymentRate": "unemployment_rate",
})
df["county_fips"] = df["county_fips"].str.strip().str.zfill(5)
df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
df["unemployment_rate"] = pd.to_numeric(df["unemployment_rate"], errors="coerce")
 
# "Adams County, Washington" -> "Adams"
df["county"] = (
    df["county_full"].str.replace(", Washington", "", regex=False)
                     .str.replace(" County", "", regex=False)
                     .str.strip()
)
df = df.drop(columns="county_full")
 
n_raw = len(df)
df = df.dropna(subset=["county_fips", "year", "unemployment_rate"]).drop_duplicates(["county_fips", "year"])
print(f"Rows: {n_raw} raw -> {len(df)} after cleaning")

Rows: 390 raw -> 390 after cleaning

In [80]:
unemployment_clean = df[['county_fips', 'year', 'unemployment_rate']]
unemployment_clean.head()

  county_fips  year  unemployment_rate
0       53001  2015                7.0
1       53001  2016                6.9
2       53001  2017                6.2
3       53001  2018                6.0
4       53001  2019                6.3

In [81]:
unemployment_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   county_fips        390 non-null    str
 1   year               390 non-null    Int64
 2   unemployment_rate  390 non-null    float64
dtypes: Int64(1), float64(1), str(1)
memory usage: 11.6 KB

In [82]:
unemployment_clean.to_csv(
    OUT_PATH,
    encoding='utf-8-sig',
    index=False
)

## Import Interest Rate

In [57]:
IN_PATH = DATA_DIR / "interest_rate.csv"
OUT_PATH = DATA_DIR / "cleaned_annual_interest_rate.csv"
START_YEAR, END_YEAR = 2015, 2024

In [58]:
# Load data set
df = pd.read_csv(IN_PATH)

In [59]:
# Clean data set
df = df.rename(columns={"observation_date": "date", "MORTGAGE30US": "rate"})
df["date"] = pd.to_datetime(df["date"], errors="coerce")
# FRED sometimes writes "." for missing values; coerce turns those into NaN
df["rate"] = pd.to_numeric(df["rate"], errors="coerce")
 
n_raw = len(df)
df = (
    df.dropna(subset=["date", "rate"])   # drop unparseable dates / missing rates
      .drop_duplicates(subset="date")    # one observation per week
      .sort_values("date")
      .reset_index(drop=True)
)
print(f"Rows: {n_raw} raw -> {len(df)} after cleaning")
# Sanity check: rates should be plausible percentages
assert df["rate"].between(0, 25).all(), "Rate outside 0-25% - check the data"

Rows: 521 raw -> 521 after cleaning

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    521 non-null    datetime64[us]
 1   rate    521 non-null    float64
dtypes: datetime64[us](1), float64(1)
memory usage: 8.3 KB

In [61]:
# Keep only the study window: 2015 - 2024
df["year"] = df["date"].dt.year
df = df[df["year"].between(START_YEAR, END_YEAR)]

In [63]:
df.head()

        date  rate  year
0 2015-01-08  3.73  2015
1 2015-01-15  3.66  2015
2 2015-01-22  3.63  2015
3 2015-01-29  3.66  2015
4 2015-02-05  3.59  2015

In [ ]:
# Aggregate weekly -> yearly
yearly = (
    df.groupby("year")["rate"]
      .agg(
          mortgage_rate_mean="mean",      # primary variable for the model
          mortgage_rate_median="median",
          mortgage_rate_min="min",
          mortgage_rate_max="max",
          n_weeks="count",
      )
      .reset_index()
)

# Year-end rate (last weekly observation of each year), as an alternative measure
yearly["mortgage_rate_yearend"] = df.groupby("year")["rate"].last().values
 
# Change in the annual average rate vs. the prior year (percentage points)
yearly["mortgage_rate_change"] = yearly["mortgage_rate_mean"].diff()
yearly = yearly.round(3)

In [65]:
# Validate
expected_years = set(range(START_YEAR, END_YEAR + 1))
assert set(yearly["year"]) == expected_years, "Missing years in output"
short = yearly[yearly["n_weeks"] < 50]
if not short.empty:
    print("WARNING: years with fewer than 50 weekly observations:\n", short[["year", "n_weeks"]])

In [66]:
# Save new file
yearly.to_csv(OUT_PATH, index=False)
print(yearly.to_string(index=False))
print(f"\nSaved to {OUT_PATH}")

 year  mortgage_rate_mean  mortgage_rate_median  mortgage_rate_min  mortgage_rate_max  n_weeks  mortgage_rate_yearend  mortgage_rate_change
 2015               3.851                 3.860               3.59               4.09       52                   4.01                   NaN
 2016               3.654                 3.590               3.41               4.32       52                   4.32                -0.197
 2017               3.990                 3.945               3.78               4.30       52                   3.99                 0.336
 2018               4.545                 4.550               3.95               4.94       52                   4.55                 0.555
 2019               3.936                 3.795               3.49               4.51       52                   3.74                -0.609
 2020               3.112                 3.070               2.66               3.72       53                   2.67                -0.824
 2021               2.958                 2.975               2.65               3.18       52                   3.11                -0.154
 2022               5.344                 5.300               3.22               7.08       52                   6.42                 2.386
 2023               6.807                 6.720               6.09               7.79       52                   6.61                 1.463
 2024               6.721                 6.775               6.08               7.22       52                   6.85                -0.086

Saved to ..\data\cleaned_annual_interest_rate.csv

## Merge Datasets

Merge Zhvi with Median Income

In [84]:
housing_df = housing_clean.merge(
    median_income_clean,
    on=["county_fips", "year"],
    how="left",
    validate="one_to_one"
)

housing_df.head()

  county_fips        county  year   average_zhvi  median_income
0       53001  Adams County  2015  139521.505277          46564
1       53001  Adams County  2016  145808.702755          47554
2       53001  Adams County  2017  155473.557623          48131
3       53001  Adams County  2018  170273.632919          49142
4       53001  Adams County  2019  184500.979061          48294

Merge with unemployment rates

In [85]:
housing_df = housing_df.merge(
    unemployment_clean,
    on=["county_fips", "year"],
    how="left",
    validate="one_to_one"
)

housing_df.head()

,county_fips,county,year,average_zhvi,median_income,unemployment_rate
0,53001,Adams County,2015,139521.505277,46564,7.0
1,53001,Adams County,2016,145808.702755,47554,6.9
2,53001,Adams County,2017,155473.557623,48131,6.2
3,53001,Adams County,2018,170273.632919,49142,6.0
4,53001,Adams County,2019,184500.979061,48294,6.3

Merge with Interest

In [87]:
housing_df = housing_df.merge(yearly, on = "year", how = "left")
housing_df.head()

,county_fips,county,year,average_zhvi,median_income,unemployment_rate,mortgage_rate_mean,mortgage_rate_median,mortgage_rate_min,mortgage_rate_max,n_weeks,mortgage_rate_yearend,mortgage_rate_change
0,53001,Adams County,2015,139521.505277,46564,7.0,3.851,3.860,3.59,4.09,52,4.01,NaN
1,53001,Adams County,2016,145808.702755,47554,6.9,3.654,3.590,3.41,4.32,52,4.32,-0.197
2,53001,Adams County,2017,155473.557623,48131,6.2,3.990,3.945,3.78,4.30,52,3.99,0.336
3,53001,Adams County,2018,170273.632919,49142,6.0,4.545,4.550,3.95,4.94,52,4.55,0.555
4,53001,Adams County,2019,184500.979061,48294,6.3,3.936,3.795,3.49,4.51,52,3.74,-0.609